mail:
  domain: aek56.com
dev-center:
   hostname: zj.aek.com
dev-test:
   hostname: ebey.aek.com

pre-test:
  authserver:
    hostname: ${dev-test.hostname}
    port: 8085
    contextPath: /apis/
  assetsserver:
    hostname: ${dev-test.hostname}
    port: 9090
    contextPath: /assets/    
  sys-web:
    hostname: ${dev-test.hostname}
    port: 8090
    contextPath: /sys/
  repair: 
    hostname: ${dev-test.hostname}
    port: 9099
    contextPath: /repair/
  redis:
    hostname: redis.aek.com
    port: 6379
    database: 10
    timeout: 0
  saas-ui:
    hostname: ${dev-test.hostname}
    port: 80
  mysql:
    hostname: dev.aek.com 
    port: 3306
    db: sd_test
    
aek56:
  registry:
    password: 'aek56.cc'

eureka:
  instance:
    preferIpAddress: true
#    ip-address: ${spring.cloud.client.ipAddress}
#    instance-id: ${spring.cloud.client.hostname}:${server.port}    
  client:
    serviceUrl:
      defaultZone: http://admin:${aek56.registry.password}@dev.aek.com:8761/eureka/,http://admin:${aek56.registry.password}@dev.aek.com:8762/eureka/    
