mail:
  domain: aek56.com
dev-center:
   hostname: 192.168.3.134  

pre-test:
  authserver:
    hostname: 192.168.3.134
    port: 8085
    contextPath: /apis/
  assetsserver:
    hostname: 192.168.3.134
    port: 9090
    contextPath: /assets/    
  sys-web:
    hostname: 192.168.3.134
    port: 8090
    contextPath: /sys/
  repair: 
    hostname: 192.168.3.134
    port: 9099
    contextPath: /repair/
  redis:
    hostname: 192.168.1.57
    port: 6379
    database: 11
    timeout: 0
  saas-ui:
    hostname: ${dev-center.hostname}
    port: 80
  mysql:
    hostname: 192.168.1.57 
    port: 3306
    db: sd_test