spring: 
  profiles: dev
  application: 
    name: assets-web-api
  session: 
    store-type: none
  redis: 
    host: 192.168.1.57
    port: 6379
    database: 0
    timeout: 0
    pool:
      max-active: 8 #最大连接数
      max-idle: 8 #最大空闲连接数
      max-wait: -1 #最大等待时间
      min-idle: 0 #初始化连接数
  #cloud:
    #client:
      #hostname: assets-web-api-dev
      #ipAddress: 192.168.3.52
  feign:
  	name: sys-web-api
	url: http://192.168.3.52:8090/
server: 
  port: 9090
db: 
  driverClassName: com.mysql.jdbc.Driver
  reader: 
    url: jdbc:mysql://192.168.1.57:3306/assets?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: root
    password: Aek56.com
  writer: 
    url: jdbc:mysql://192.168.1.57:3306/assets?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: root
    password: Aek56.com
  initialSize: 20
  maxActive: 40
  maxIdle: 20
  minIdle: 1
  maxWaitMillis: 60000
  timeBetweenEvictionRunsMillis: 3000
  minEvictableIdleTimeMillis: 300000
  maxPoolPreparedStatementPerConnectionSize: 20
druid: 
  filters: stat
  logType: log4j2

eureka: 
  instance:
    status-page-url-path: /swagger-ui.html
    preferIpAddress: true
    ip-address: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.cloud.client.hostname}:${server.port}    
  client: 
    serviceUrl: 
      defaultZone: http://register-center:19512/eureka/,http://register-center:19511/eureka/
 
jwt:
  header: X-AEK56-Token
  secret: aek56.com
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
---
spring: 
  profiles: test
  application: 
    name: assets-web-api
  session: 
    store-type: none
  redis: 
    host: ${pre-test.redis.hostname}
    port: ${pre-test.redis.port}
    database: ${pre-test.redis.database}
    timeout: ${pre-test.redis.timeout}
    pool:
      max-active: 8 #最大连接数
      max-idle: 8 #最大空闲连接数
      max-wait: -1 #最大等待时间
      min-idle: 0 #初始化连接数
  cloud:
    client:
      hostname: ${dev-center.hostname}
      ipAddress: 192.168.3.134      

server: 
  port: 9090
db: 
  driverClassName: com.mysql.jdbc.Driver
  reader: 
    url: jdbc:mysql://dev.aek.com:3306/assets_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: root
    password: Aek56.com
  writer: 
    url: jdbc:mysql://dev.aek.com:3306/assets_test?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: root
    password: Aek56.com
  initialSize: 20
  maxActive: 40
  maxIdle: 20
  minIdle: 1
  maxWaitMillis: 60000
  timeBetweenEvictionRunsMillis: 3000
  minEvictableIdleTimeMillis: 300000
  maxPoolPreparedStatementPerConnectionSize: 20
druid: 
  filters: stat
  logType: log4j2

eureka: 
  instance:
    preferIpAddress: true
    status-page-url-path: /swagger-ui.html
    ip-address: ${spring.cloud.client.ipAddress}
    instance-id: ${spring.cloud.client.hostname}:${server.port} 
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30      
  client: 
    serviceUrl: 
      defaultZone: http://ebey.aek.com:19513/eureka/,http://ebey.aek.com:19514/eureka/

jwt:
  header: X-AEK56-Token
  secret: aek56.com
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh
