eureka:
# Register our microservices to Eureka using hostnames in a Docker environment will not work, they will all get 
# one and the same hostname. Instead we configure them to use its IP address during registration with Eureka.
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://register-center:8778/eureka/

security:
  user:
    password: password 
    
spring:
  datasource:
    url: jdbc:mysql://config-center:3306/auth
    username: root
    password: ibase4j
    driver-class: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create
      
server:
  port: 18899
  contextPath: /userauth 
