server:
  contextPath: ${aek.auth-server.contextPath} 
  port: ${aek.auth-server.port}

spring:
  profiles: uat
  datasource:
    url: jdbc:mysql://${aek.mysql.sys.writer.hostname}:${aek.mysql.sys.writer.port}/${aek.mysql.sys.writer.database}?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: ${aek.mysql.sys.writer.username}
    password: ${aek.mysql.sys.writer.password}
    driver-class: com.mysql.jdbc.Driver    
  redis:
    host: ${aek.redis.hostname}
    port: ${aek.redis.port}
    database: ${aek.redis.database}
    timeout: ${aek.redis.timeout}
    pool:
      max-active: 8 #最大连接数
      max-idle: 8 #最大空闲连接数
      max-wait: -1 #最大等待时间
      min-idle: 0 #初始化连接数
---
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://mysqlcluster.aek.com:3306/sd_dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false
    username: '{cipher}57a8624ebc8f8779b5c0d525859b816a6d739dde6f96190299ccdad808052b6e'
    password: '{cipher}57a8624ebc8f8779b5c0d525859b816a6d739dde6f96190299ccdad808052b6e'
    driver-class: com.mysql.jdbc.Driver    
  redis:
    #database: 0
    host: redis.aek.com
    #password: # Login password of the redis server.
    port: 6379
    timeout: 0
    pool:
      max-active: 8 #最大连接数
      max-idle: 8 #最大空闲连接数
      max-wait: -1 #最大等待时间
      min-idle: 0 #初始化连接数
     
server:
  contextPath: /apis 
  port: 8085
