server:
  port: 19090



refreshtest: app is running in docker
#spring:
#  profiles: test
  
eureka:
  instance: 
  leaseRenewalIntervalInSeconds: 1
  leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://register-center:8778/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
      
---

# api-gateway instance when used on Docker
spring:
  profiles: docker
eureka:
# Register our microservices to Eureka using hostnames in a Docker environment will not work, they will all get 
# one and the same hostname. Instead we configure them to use its IP address during registration with Eureka.
  instance:
    preferIpAddress: true
  client:
    serviceUrl:
      defaultZone: http://register-center:8761/eureka/
