server:
  port: 9090



refreshtest: zj@aek56.com
#spring:
#  profiles: test
  
eureka:
  instance: 
  leaseRenewalIntervalInSeconds: 1
  leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://clock-builder.com:18887/eureka/
    healthcheck:
      enabled: true
    lease:
      duration: 5
      
jwt:
  header: X-AEK56-Token
  secret: aek56.com
      
---

# api-gateway instance when used on Docker
spring:
  profiles: docker
eureka:
# Register our microservices to Eureka using hostnames in a Docker environment will not work, they will all get 
# one and the same hostname. Instead we configure them to use its IP address during registration with Eureka.
  instance:
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    serviceUrl:
      defaultZone: http://192.168.59.103:8761/eureka/
