spring:
  application:
    name: eurekaService
#  profiles:
#    active: eurekaService1
security:
  basic:
    enabled: true     # 开启基于HTTP basic的认证
  user:
    name: aek56      # 配置登录的账号是user
    password: aek56123   # 配置登录的密码是aek56123


# 配置三个实例的eureka高可用配置，如果是在swarm集群中服务，请把swarm中我service名称部署为三个，分别为：eurekaServer1,eurekaServer2,eurekaServer3
---
spring:
  profiles: eurekaService1
server:
  port: 9511                    # 指定该Eureka实例的端口
eureka:
  instance:
    hostname: eurekaServer1         # 指定该Eureka实例的主机名
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port} # 将Instance ID设置成IP:端口的形式
  client:
    registerWithEureka: false   #自己不需要注册
    fetchRegistry: false    
    serviceUrl:    #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://aek56:aek56123@eurekaServer2:19512/eureka/,http://aek56:aek56123@eurekaServer3:19513/eureka/

---
spring:
  profiles: eurekaService2
server:
  port: 9512                    # 指定该Eureka实例的端口
eureka:
  instance:
    hostname: eurekaServer2         # 指定该Eureka实例的主机名
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka： false
    fetchRegistry: false
    serviceUrl:    #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://aek56:aek56123@eurekaServer1:9511/eureka/,http://aek56:aek56123@eurekaServer3:9513/eureka/

---
spring:
  profiles: eurekaServer3
server:
  port: 9513                    # 指定该Eureka实例的端口
eureka:
  instance:
    hostname: eurekaServer3         # 指定该Eureka实例的主机名
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:    #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。
      defaultZone: http://aek56:aek56123@eurekaServer2:9512/eureka/,http://aek56:aek56123@eurekaServer1:9511/eureka/