spring:
  profiles: docker
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://docker:8778/eureka/

zuul:
  prefix: /api
#  Uncomment to disable services automatically registering in Zuul
#  ignoredServices: '*'

  routes:
    echo-service: /hello/**


#management:
#  security:
 #   enabled: false
server:
  port: 19091