spring: 
  profiles: uat
  redis: 
    host: ${aek.redis.hostname}
    port: ${aek.redis.port}
    database: ${aek.redis.database}
    timeout: ${aek.redis.timeout}
    pool:
      max-active: 8 #最大连接数
      max-idle: 8 #最大空闲连接数
      max-wait: -1 #最大等待时间
      min-idle: 0 #初始化连接数  

server: 
  port: ${aek.repair-server.port}

db: 
  driverClassName: com.mysql.jdbc.Driver
  reader: 
    url: jdbc:mysql://${aek.mysql.repair.reader.hostname}:${aek.mysql.repair.reader.port}/${aek.mysql.repair.reader.database}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: ${aek.mysql.repair.reader.username}
    password: ${aek.mysql.repair.reader.password}
  writer: 
    url: jdbc:mysql://${aek.mysql.repair.writer.hostname}:${aek.mysql.repair.writer.port}/${aek.mysql.repair.writer.database}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: ${aek.mysql.repair.writer.username}
    password: ${aek.mysql.repair.writer.password}
  initialSize: 20
  maxActive: 40
  maxIdle: 20
  minIdle: 1
  maxWaitMillis: 60000
  timeBetweenEvictionRunsMillis: 3000
  minEvictableIdleTimeMillis: 300000
  maxPoolPreparedStatementPerConnectionSize: 20
