spring:
  profiles: uat

server:
  port: ${aek.saas-ui.port} 
  
zuul:
  routes:
    servlet-path: /zuul
    ignoredServices: '*'
    assets-web-api: /api/assets/**
    auth-server: /api/api_v3/**
    sys-web-api: /api/sys/**
    repair-web-api: /api/repair/**
    #aek-fileserver-api: /api/upload/**
    aek-fileserver-api: /api/file/**
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  sensitiveHeader:  
  SendResponseFilter:
    post:
      disable: false    
      
logging: 
  file: ./logs/saas-ui.log
  pattern:
    file: "%date{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %level [%c{36}.%M:%L] - %msg%xEx%n"
    console: "%date{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %level [%c{36}.%M:%L] - %msg%xEx%n"
  level:
     root: INFO
     com.aek56: debug
     com.netflix: ERROR
     org:
       springframework:
         security: DEBUG


