spring:
  profiles: uat

server:
  port: ${aek.saas-ui.port} 
  
zuul:
  routes:
    servlet-path: /zuul
    #ignoredServices: '*'
    assets-web-api: /api/assets/**
    auth-server: /api/api_v3/**
    sys-web-api: /api/sys/**
    repair-web-api: /api/repair/**
    #aek-fileserver-api: /api/upload/**
    aek-fileserver-api: /api/file/**
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  sensitiveHeader:  
  SendResponseFilter:
    post:
      disable: false    


