spring:
  profiles: uat

server:
  port: ${aek.saas-ui.port} 
  
zuul:
  prefix: /api
  routes:
    servlet-path: /zuul
    #ignoredServices: '*'
    #assets-web-api: /api/assets/**
    #auth-server: /api/api_v3/**
    #sys-web-api: /api/sys/**
    #repair-web-api: /api/repair/**
    #aek-fileserver-api: /api/upload/**
    #aek-fileserver-api: /api/file/**
    
    assets-web-api: 
#      path: /api/assets/**
      path: /assets/**
      stripPrefix: false
      serviceId: assets-web-api
    auth-server: 
#      path: /api/api_v3/**
      path: /api_v3/**
      stripPrefix: true
      url: http://192.168.1.48:8085/apis/
    sys-web-api: 
#      path: /api/sys/**
      path: /sys/**
      stripPrefix: false
      serviceId: sys-web-api
    repair-web-api: 
      path: /repair/**
      stripPrefix: false
      serviceId: repair-web-api
    #aek-fileserver-api: /api/upload/**
    aek-fileserver-api: 
      path: /file/**
      stripPrefix: false
      serviceId: aek-fileserver-api
      
  max:
    host:
      connections: 500
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  sensitiveHeader:  
  SendResponseFilter:
    post:
      disable: false    


