spring:
  profiles: uat
  session:
    store-type: none
  redis: 
    host: ${aek.redis.hostname}
    port: ${aek.redis.port}
    database: ${aek.redis.database}
    timeout: ${aek.redis.timeout}
    pool:
      max-active: 8 #最大连接数
      max-idle: 8 #最大空闲连接数
      max-wait: -1 #最大等待时间
      min-idle: 0 #初始化连接数

server:
  port: ${aek.sys-server.port}

db: 
  driverClassName: com.mysql.jdbc.Driver
  reader: 
    url: jdbc:mysql://${aek.mysql.sys.reader.hostname}:${aek.mysql.sys.reader.port}/${aek.mysql.sys.reader.database}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: ${aek.mysql.sys.reader.username}
    password: ${aek.mysql.sys.reader.password}
  writer: 
    url: jdbc:mysql://${aek.mysql.sys.writer.hostname}:${aek.mysql.sys.writer.port}/${aek.mysql.sys.writer.database}?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&serverTimezone=PRC&useSSL=false
    username: ${aek.mysql.sys.writer.username}
    password: ${aek.mysql.sys.writer.password}
  initialSize: 20
  maxActive: 40
  maxIdle: 20
  minIdle: 1
  maxWaitMillis: 60000
  timeBetweenEvictionRunsMillis: 3000
  minEvictableIdleTimeMillis: 300000
  maxPoolPreparedStatementPerConnectionSize: 20
druid: 
  filters: stat
  logType: log4j2


