server:
  port: 8099

  
author: zj@aek56.com

eureka:
  client:
    serviceUrl:
      defaultZone: http://register-center:8778/eureka/

# The OAuth2 server definition that would be used to send the authorization requests to
authserver:
    hostname: authserver
    port: 18899
    contextPath: userauth

# Note that the "/user" endpoint needs to provide the principle of the logged in user (/me endpoint)
spring:
  oauth2:
    resource: 
      userInfoUri: http://${authserver.hostname}:${authserver.port}/${authserver.contextPath}/me
      preferTokenInfo: false 
